export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_WRONG_CREDENTIALS = "LOGIN_USER_WRONG_CREDENTIALS";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';

export const CLEAR_REGISTER = "CLEAR_REGISTER";