openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 191 characters.'
                  example: gllyvysnqgjkjnibdzeqbgkjhznaxpshfvfxfrneqtupzxfvglqpzmyjmerpxyksxyy
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 191 characters.'
                  example: kmzbfnccjftnzatevujwpvjomcmvnkpasbxwxtiweojxapbbxlgudcjvjjsdvxojczfkpxedqmntxgqcvjrmqurgvczqoklyfmkrgmwcnhaq
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: hkuar
              required:
                - name
                - email
                - password
      security: []
  /api/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must not be greater than 191 characters.'
                  example: ubuifmzldfddphhuapsktlaprbzdzcdgdkestemrdxjfiyhk
                password:
                  type: string
                  description: ''
                  example: eveniet
              required:
                - email
                - password
      security: []
  /api/user:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
